language: node_js

node_js: 
  - '14'

# Start the docker engine for building docker images
services:
  - docker

# Only if you have your server in a subdirectory
before_install:
  - cd server

# Install dependencies
install:
  - yarn install

# Only run if you have tests
script:
  - yarn test

# Get the ssh key for your instance
before-deploy:
  - openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

# Build Docker image and deploy to instance
deploy:
  provider: script
  script: bash deploy.sh
  on: 
    branch: main